name: stock_market_app
description: This projet is called Stocket and it is a stock market mobile application.
publish_to: 'none'
version: 0.0.0
environment:
  sdk: '>=3.1.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/stocket-logo.png"
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/