name: stock_market_app
description: This project is called Stocket and it is a stock market mobile application.
publish_to: 'none'
version: 0.0.0
environment:
  sdk: '>=3.1.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.2
  animated_digit: ^3.2.3
  http: ^1.1.0
  firebase_core: ^2.16.0
  firebase_auth: 4.10.0
  cloud_firestore: ^4.9.2
  intl: ^0.17.0
  keyboard_dismisser: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/stocket-logo.png"
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/