// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3HRwvnKfJRuq0996XwNtHidvKOwc7JXM',
    appId: '1:942240348446:web:c1414f5128a4754603710f',
    messagingSenderId: '942240348446',
    projectId: 'stock-market-db-b5abf',
    authDomain: 'stock-market-db-b5abf.firebaseapp.com',
    storageBucket: 'stock-market-db-b5abf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRX4gwVIaZcvgMs4k04h70699weLrijuc',
    appId: '1:942240348446:android:3725ca4515f4298903710f',
    messagingSenderId: '942240348446',
    projectId: 'stock-market-db-b5abf',
    storageBucket: 'stock-market-db-b5abf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaZmWofCXUQQBNdzxhxffaTfvilov2IJ8',
    appId: '1:942240348446:ios:79ca8e316a75dff503710f',
    messagingSenderId: '942240348446',
    projectId: 'stock-market-db-b5abf',
    storageBucket: 'stock-market-db-b5abf.appspot.com',
    iosBundleId: 'com.example.stockMarketApp.RunnerTests',
  );
}
